### ISSUE TITLE
Boulder container restarting - panic: opening hierarchy directory

### ISSUE THREAD

**Issue by eddor** [hakwerk/labca#126]
Hello
I'm having this error on docker mode install:

boulder-1  | panic: opening hierarchy directory: open /hierarchy: no such file or directory
boulder-1  |
boulder-1  | goroutine 1 [running]:
boulder-1  | github.com/letsencrypt/boulder/cmd.Fail(...)
boulder-1  | 	/go/src/github.com/letsencrypt/boulder/cmd/shell.go:399
boulder-1  | github.com/letsencrypt/boulder/cmd.FailOnError({0xd80600, 0xc0004b5560}, {0xc6e698?, 0x0?})
boulder-1  | 	/go/src/github.com/letsencrypt/boulder/cmd/shell.go:412 +0xd4
boulder-1  | main.main()
boulder-1  | 	/go/src/github.com/letsencrypt/boulder/test/aia-test-srv/main.go:51 +0x10e
boulder-1  | Starting service boulder-publisher-1
boulder-1  | Starting service boulder-remoteva-b
boulder-1  | Starting service s3-test-srv
boulder-1  | Starting service ct-test-srv
boulder-1  | Starting service boulder-remoteva-a
boulder-1  | Starting service nonce-service-taro-2
boulder-1  | Starting service akamai-test-srv
boulder-1  | Starting service boulder-publisher-2
boulder-1  | Starting service nonce-service-taro-1
boulder-1  | Starting service nonce-service-zinc-1
boulder-1  | Starting service log-validator
boulder-1  | Starting service boulder-sa-1
boulder-1  | Starting service mail-test-srv
boulder-1  | Starting service aia-test-srv
boulder-1  |
boulder-1  |
boulder-1  | These processes exited early (check above for their output):
boulder-1  | 	'('./bin/aia-test-srv', '--addr', ':4502', '--hierarchy', '/hierarchy')' with pid 254 exited 2
boulder-1 exited with code 1

I recently changed from a regular install to a docker one.
I only realized of the error because certificate for web ui itself expired.
Is there anything I can do to fix it?
Thanks in advance.

**Comment by hakwerk** [comment]
Do you have the latest version (v24.04)? I thought I had fixed that issue in [this commit](https://github.com/hakwerk/labca/commit/e6da46b9af1b579e9003202a5a4f64fe690daab9).

You can try to make the same edit to your local `docker-compose.yml` file: add a volume "- certificates:/hierarchy" to the boulder container and declare the container "certificates:" near the bottom

**Comment by eddor** [comment]
that solved the problem.
Thank you very much

**Comment by eddor** [comment]
a volume was missing on my docker-compose.yml
