### ISSUE TITLE
Issue in installing/configure labca

### ISSUE THREAD

**Issue by FilipFrancis** [hakwerk/labca#25]
Hi,
I have been trying to install labca  but i am keep getting the following error whith the last step in the web interface
Mon Oct 18 03:26:24 UTC 2021
Parsing account key...
Parsing CSR...
Found domains: labca00.localdomain.be
Getting directory...
Traceback (most recent call last):
  File "/home/labca/acme_tiny.py", line 197, in <module>
    main(sys.argv[1:])
  File "/home/labca/acme_tiny.py", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/home/labca/acme_tiny.py", line 105, in get_crt
    directory, _, _ = _do_request(directory_url, err_msg="Error getting directory")
  File "/home/labca/acme_tiny.py", line 45, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error getting directory:
Url: http://labca00.localdomain.be/directory
Data: None
Response Code: 502
Response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html

I see a docker running on port 4001 but when i go to the web labca00.localdomain.be/direcotry its giving me Bad Gateway
and i do not know where or why its giving me this its really the last step in the web interface where its creating a Certificate 
So please help
Filip

**Comment by FilipFrancis** [comment]
Hi,
thanks for the response
here you have the log
boulder_1  | GOBIN=/go/src/github.com/letsencrypt/boulder/bin GO111MODULE=on go install -mod=vendor -tags "integration" ./...
boulder_1  | cp /go/src/github.com/letsencrypt/boulder/bin/boulder-va /go/src/github.com/letsencrypt/boulder/bin/boulder-remoteva
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Creating HTTP-01 challenge server on 10.77.77.77:5002
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Creating HTTPS HTTP-01 challenge server on 10.77.77.77:5001
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Creating TCP and UDP DNS-01 challenge server on :8053
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Creating TCP and UDP DNS-01 challenge server on :8054
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Creating TLS-ALPN-01 challenge server on 10.88.88.88:5001
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Answering A queries with 10.77.77.77 by default
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Starting challenge servers
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:22 Starting management server on :8055
boulder_1  | I211018083122 ocsp-responder hPmR3gw Versions: ocsp-responder=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | I211018083122 boulder-remoteva 4IHrgQI Versions: boulder-remoteva=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to va1.boulder:9097 health service
boulder_1  | I211018083123 boulder-publisher 2qGVqgQ Versions: boulder-publisher=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to publisher2.boulder:9091 health service
boulder_1  | got error connecting to health service publisher2.boulder:9091: grpc.health.v1.Health.Check timed out after 997 ms
boulder_1  | Connecting to publisher2.boulder:9091 health service
boulder_1  | E211018083124 boulder-publisher -NnxxwY [AUDIT] [core]grpc: Server.Serve failed to complete security handshake from "10.88.88.88:44368": EOF
boulder_1  | I211018083124 boulder-sa oYbu2w8 Versions: boulder-sa=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to sa2.boulder:9095 health service
boulder_1  | I211018083124 nonce-service p-zwfwA Versions: nonce-service=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to nonce1.boulder:9101 health service
boulder_1  | I211018083125 nonce-service p-zwfwA Versions: nonce-service=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to nonce2.boulder:9101 health service
boulder_1  | I211018083125 boulder-publisher 2qGVqgQ Versions: boulder-publisher=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to publisher1.boulder:9091 health service
boulder_1  | got error connecting to health service publisher1.boulder:9091: grpc.health.v1.Health.Check timed out after 997 ms
boulder_1  | Connecting to publisher1.boulder:9091 health service
boulder_1  | E211018083126 boulder-publisher 3PeqsQ8 [AUDIT] [core]grpc: Server.Serve failed to complete security handshake from "10.77.77.77:50366": EOF
boulder_1  | I211018083126 log-validator g5CP7Ac Waiting for /var/log/boulder-wfe2.log to appear...
boulder_1  | I211018083126 log-validator 44ONuAY Waiting for /var/log/boulder-wfe.log to appear...
boulder_1  | I211018083126 log-validator 5fDH5gY Waiting for /var/log/ocsp-updater.log to appear...
boulder_1  | I211018083126 log-validator 67f_wwg Waiting for /var/log/boulder-ra.log to appear...
boulder_1  | I211018083126 boulder-sa oYbu2w8 Versions: boulder-sa=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | Connecting to sa1.boulder:9095 health service
boulder_1  | 2021/10/18 08:31:27 ct-test-srv on :4510 with pubkey MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyw1HymhJkuxSIgt3gqW3sVXqMqB3EFsXcMfPFo0vYwjNiRmCJDXKsR0Flp7MAK+wc3X/7Hpc8liUbMhPet7tEA==
boulder_1  | 2021/10/18 08:31:27 ct-test-srv on :4501 with pubkey MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKtnFevaXV/kB8dmhCNZHmxKVLcHX1plaAsY9LrKilhYxdmQZiu36LvAvosTsqMVqRK9a96nC8VaxAdaHUbM8EA==
boulder_1  | 2021/10/18 08:31:27 ct-test-srv on :4511 with pubkey MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFRu37ZRLg8lT4rVQwMwh4oAOpXb4Sx+9hgQ+JFCjmAv3oDV+sDOMsC7hULkGTn+LB5L1SRo/XIY4Kw5V+nFXgg==
boulder_1  | 2021/10/18 08:31:27 ct-test-srv on :4512 with pubkey MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFRu37ZRLg8lT4rVQwMwh4oAOpXb4Sx+9hgQ+JFCjmAv3oDV+sDOMsC7hULkGTn+LB5L1SRo/XIY4Kw5V+nFXgg==
boulder_1  | 2021/10/18 08:31:27 ct-test-srv on :4500 with pubkey MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYggOxPnPkzKBIhTacSYoIfnSL2jPugcbUKx83vFMvk5gKAz/AGe87w20riuPwEGn229hKVbEKHFB61NIqNHC3Q==
boulder_1  | I211018083127 boulder-ca 1qy86gY Versions: boulder-ca=(Unspecified Unspecified) Golang=(go1.16.6) BuildHost=(Unspecified)
boulder_1  | I211018083127 boulder-ca ipP_lgg loading hostname policy, sha256: bf84e84b0646bae2569cc5476dd43f1be9ae76422a48913884be1acef8df703a
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1005 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1001 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 996 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 995 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 999 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1001 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 995 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | E211018083136 boulder-ca qM-tDQA [AUDIT] Couldn't load issuers: failed to create lint issuer: x509: requested SignatureAlgorithm does not match private key type
boulder_1  | Couldn't load issuers: failed to create lint issuer: x509: requested SignatureAlgorithm does not match private key type
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 850 ms
boulder_1  | E211018083137 health-checker xIqPkwY [AUDIT] timed out waiting for ca1.boulder:9093 health check
boulder_1  | timed out waiting for ca1.boulder:9093 health check
boulder_1  | Starting service ocsp-responder
boulder_1  | Starting service sd-test-srv
boulder_1  | Starting service boulder-remoteva-a
boulder_1  | Starting service boulder-publisher-2
boulder_1  | Starting service boulder-sa-2
boulder_1  | Starting service nonce-service-taro
boulder_1  | Starting service nonce-service-zinc
boulder_1  | Starting service akamai-test-srv
boulder_1  | Starting service boulder-publisher-1
boulder_1  | Starting service log-validator
boulder_1  | Starting service boulder-sa-1
boulder_1  | Starting service ct-test-srv
boulder_1  | Waiting for debug port 4500 (./bin/ct-test-srv --config test/ct-test-srv/ct-test-srv.json)
boulder_1  | Starting service boulder-ca-a
boulder_1  | Error starting service boulder-ca-a: Command '['./bin/health-checker', '-addr', 'ca1.boulder:9093', '-config', 'labca/config/health-checker.json']' returned non-zero exit status 1.
boulder_1  | I211018083137 boulder-sa kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 boulder-sa kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 boulder-sa htX9nwc Exiting
boulder_1  | I211018083137 log-validator kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 log-validator htX9nwc Exiting
boulder_1  | I211018083137 boulder-publisher kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 boulder-publisher htX9nwc Exiting
boulder_1  | I211018083137 nonce-service kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 nonce-service htX9nwc Exiting
boulder_1  | I211018083137 nonce-service kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 nonce-service htX9nwc Exiting
boulder_1  | I211018083137 boulder-sa kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 boulder-sa htX9nwc Exiting
boulder_1  | I211018083137 boulder-publisher kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 boulder-publisher htX9nwc Exiting
boulder_1  | I211018083137 boulder-remoteva kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 boulder-remoteva htX9nwc Exiting
boulder_1  | I211018083137 ocsp-responder kKG6cwA Caught SIGTERM
boulder_1  | I211018083137 ocsp-responder htX9nwc Exiting
boulder_1  | 2021/10/18 08:31:37 Caught SIGTERM
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 Caught signals. Shutting down
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 http: Server closed
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 http: Server closed
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 http: Server closed
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 Shutting down management server
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 http: Server closed
boulder_1  | pebble-challtestsrv - 2021/10/18 08:31:37 Goodbye!
boulder_1  | 2021/10/18 08:31:37 Exiting
