### ISSUE TITLE
Final restart fails due to "Name or Service not known" errors

### ISSUE THREAD

**Issue by mw8088** [hakwerk/labca#50]
Hello, when the WebGUI reaches the final setup phase, it displays an error "Name or service not found" when trying to get the acme challenge. Here are the logs from that page.

acme-tiny.log
```
Mon Jul 11 16:13:18 UTC 2022
Parsing account key...
Parsing CSR...
Found domains: labca.domain
Getting directory...
Directory found!
Registering account...
Already registered! Account ID: http://boulder:4001/acme/acct/1
Creating new order...
Order created!
Verifying labca.domain...
Traceback (most recent call last):
  File "/labca/acme_tiny.py", line 145, in get_crt
    assert (disable_check or _do_request(wellknown_url)[0] == keyauthorization)
  File "/labca/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error:
Url: http://labca.domain/.well-known/acme-challenge/<challenge>
Data: None
Response Code: None
Response: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/labca/acme_tiny.py", line 199, in <module>
    main(sys.argv[1:])
  File "/labca/acme_tiny.py", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
  File "/labca/acme_tiny.py", line 147, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to /var/www/html/.well-known/acme-challenge/<challenge>, but couldn't download http://labca.domain/.well-known/acme-challenge/<challenge>: Error:
Url: http://labca.domain/.well-known/acme-challenge/<challenge>
Data: None
Response Code: None
Response: <urlopen error [Errno -2] Name or service not known>

```
commander.log
```
Container boulder-nginx-1  Restarting
Container boulder-bmysql-1  Restarting
Container boulder-bmysql-1  Started
Container boulder-labca-1  Restarting
Container boulder-boulder-1  Restarting
Container boulder-nginx-1  Started
Container boulder-labca-1  Started
Container boulder-boulder-1  Started
```

**Comment by hakwerk** [comment]
Looks like DNS is not set up correctly? You probably get the same error message if you do this in a terminal on your LabCA machine:
```
ping labca.domain
```

Note that it will **not** be sufficient to add something to your /etc/hosts file, as the boulder server running in docker will also need to be able to resolve via DNS, or it will result in one of [these errors](https://github.com/hakwerk/labca#common-error-messages)

**Comment by mw8088** [comment]
That was the issue, thanks!
