### ISSUE TITLE
broken setup

### ISSUE THREAD

**Issue by ediazcomellas** [hakwerk/labca#7]
Hi,
Great project. I've tried to get it working in debian 10 but unfortunately it breaks during the initial setup.

I was able to get to the second web page of the setup. After seting the domain name and the dns server, the docker container "boulder_boulder_1" fails and restarts.

628365fc7056 letsencrypt/boulder-tools-go1.15:2020-08-12 "labca/entrypoint.sh" 16 minutes ago Restarting (1) 54 seconds ago boulder_boulder_1

Stoping and starting does not help. The web page shows "could not render requested page".

docker logs shows:
Starting enhanced syslogd: rsyslogd.
Connected to boulder-mysql:3306
Database boulder_sa_test already exists - skipping create
goose: no migrations to run. current version: 20200609125504
migrated boulder_sa_test database with ./sa/_db/
added users to boulder_sa_test
Database boulder_sa_integration already exists - skipping create
goose: no migrations to run. current version: 20200609125504
migrated boulder_sa_integration database with ./sa/_db/
added users to boulder_sa_integration
created all databases
CKR_SLOT_ID_INVALID: Slot 0 does not exist.
ERROR: Could open the PKCS#8 file: labca/test-ca.p8
Found slot 864150829 with matching token label.
Starting enhanced syslogd: rsyslogd.
Connected to boulder-mysql:3306
Database boulder_sa_test already exists - skipping create
goose: no migrations to run. current version: 20200609125504
migrated boulder_sa_test database with ./sa/_db/
added users to boulder_sa_test
Database boulder_sa_integration already exists - skipping create
goose: no migrations to run. current version: 20200609125504
migrated boulder_sa_integration database with ./sa/_db/
added users to boulder_sa_integration
created all databases
CKR_SLOT_ID_INVALID: Slot 0 does not exist.
ERROR: Could open the PKCS#8 file: labca/test-ca.p8
Found slot 864150829 with matching token label.

I can't imagine how to fix it to get it working.

I would gladly provide any required information to sort the problem.

**Comment by ediazcomellas** [comment]
I repeated the setup and catched a log when the problem happened:

labca_1    | 2020/11/05 20:06:59 errorHandler: templates: ExecuteTemplate error, baseView 'base.tmpl' view 'views/cert.tmpl': template: partials/progress.tmpl:53:91: executing "body" at <(ne .Organization "") and (not .IsRoot)>: can't give argument to non-function ne .Organization ""

**Comment by hakwerk** [comment]
Thanks for reporting these issues! I have fixed the code, so please try running the install script again and it should work now.

**Comment by ediazcomellas** [comment]
Almost got it working. 

It now get's stuck in the final phase (/admin/final):
After a while saying: "Almost there!..." it comes with an "OOPS Some unexpected error ocurred!"
There you can see the error message:

labca_1    | 2020/11/08 12:22:45 GET /
labca_1    | 2020/11/08 12:22:45 GET /setup
labca_1    | 2020/11/08 12:22:45 GET /final
labca_1    | 2020/11/08 12:22:45 GET /final
labca_1    | 2020/11/08 12:22:56 ERROR: Message from server: 'ERROR! On line 58 in commander script
labca_1    | '
labca_1    | 2020/11/08 12:22:56 errorHandler: ERROR! On line 58 in commander script
labca_1    | main._hostCommand(0xc466e0, 0xc0000e47e0, 0xc00018f100, 0xb7d266, 0xc, 0x0, 0x0, 0x0, 0xba9100)
labca_1    |     /go/src/labca/main.go:1510 +0x649
labca_1    | main.finalHandler(0xc466e0, 0xc0000e47e0, 0xc00018f100)
labca_1    |     /go/src/labca/main.go:1857 +0xf9
labca_1    | net/http.HandlerFunc.ServeHTTP(0xba8868, 0xc466e0, 0xc0000e47e0, 0xc00018f100)
labca_1    |     /usr/local/go/src/net/http/server.go:2042 +0x44
labca_1    | main.authorized.func1(0xc466e0, 0xc0000e47e0, 0xc00018f100)
labca_1    |     /go/src/labca/main.go:2313 +0x230
labca_1    | net/http.HandlerFunc.ServeHTTP(0xc0002478a0, 0xc466e0, 0xc0000e47e0, 0xc00018f100)
labca_1    |     /usr/local/go/src/net/http/server.go:2042 +0x44
labca_1    | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003b00c0, 0xc466e0, 0xc0000e47e0, 0xc00018e800)
labca_1    |     /go/src/github.com/gorilla/mux/mux.go:210 +0xd3
labca_1    | net/http.serverHandler.ServeHTTP(0xc0000e4380, 0xc466e0, 0xc0000e47e0, 0xc00018e800)
labca_1    |     /usr/local/go/src/net/http/server.go:2843 +0xa3
labca_1    | net/http.(*conn).serve(0xc00038d180, 0xc47ea0, 0xc0004db800)
labca_1    |     /usr/local/go/src/net/http/server.go:1925 +0x8ad
labca_1    | created by net/http.(*Server).Serve
labca_1    |     /usr/local/go/src/net/http/server.go:2969 +0x36c
labca_1    | 2020/11/08 12:22:56 http: superfluous response.WriteHeader call from main.finalHandler (main.go:1858)

**Comment by hakwerk** [comment]
Could you check your /etc/nginx/ssl/acme_tiny.log for any further details on the issue please?

**Comment by ediazcomellas** [comment]
This is what appears:


dom nov  8 17:41:51 CET 2020
Parsing account key...
Parsing CSR...
Found domains: ca.central.local
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying ca.central.local...
Traceback (most recent call last):
  File "/home/labca/acme_tiny.py", line 197, in <module>
    main(sys.argv[1:])
  File "/home/labca/acme_tiny.py", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/home/labca/acme_tiny.py", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for ca.central.local: {u'status': u'invalid', u'challenges': [{u'status': u'invalid', u'url': u'https://ca.central.local/acme/chall-v3/10/Q9qu8Q', u'token': u'e7V8iNMbJqQH8mOUW97Hzbd6Is5446O2nl91p-3jiQU', u'type': u'http-01', u'error': {u'status': 400, u'type': u'urn:ietf:params:acme:error:dns', u'detail': u'DNS problem: query timed out looking up A for ca.central.local'}}], u'identifier': {u'type': u'dns', u'value': u'ca.central.local'}, u'expires': u'2020-11-15T16:41:52Z'}


Despite that, I can ping ca.central.local and it resolves correctly. I can also query the dns server I configured in the initial setup (using "dig ca.central.local @ip_address_of_dns_server") and it resolves OK.

**Comment by hakwerk** [comment]
Hmm, so the boulder component cannot resolve the address, is there anything useful in the boulder logs (cd /home/labca/boulder; docker-compose logs boulder) when you retry this? I'm not able to reproduce the problem.

You might also try increasing the dnsTimeout in /home/labca/boulder_labca/config/va*.json to "10s" or so and then restart boulder (docker-compose restart boulder).

**Comment by ediazcomellas** [comment]
It was an issue with the DNS server. I replaced the AD DNS server with a clean linux  bind9, just for this test, and it works without any problem. 

Thanks a lot!

**Comment by sakis-tech** [comment]
Hello, have the same problem as described above.

```
Restart
Almost there! Now we will request a certificate for this website and restart one more time ... 
```
and then it comes

```
OOPS

Some unexpected error occurred!
```

I use pihole as an internal dns and DHCP server. do I have to pay attention to something, or is it enough if I just enter the IP of the pihole?

When I run `docker-compose restart boulder `I get the following error message. 

```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[1791] Failed to execute script docker-compose


```

**Comment by sakis-tech** [comment]
Hello, have the same problem as described above.

```
Restart
Almost there! Now we will request a certificate for this website and restart one more time ... 
```
and then it comes

```
OOPS

Some unexpected error occurred!
```

I use pihole as an internal dns and DHCP server. I entered all of my LXC as local DNS records in the pihole, including labca. Do I have to pay attention to something?

here is a section from my `/etc/nginx/ssl/acme_tiny.log`

```
Di 27. Jul 23:50:04 CEST 2021
Parsing account key...
Parsing CSR...
Found domains: ca.home.domain.com
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying ca.home.domain.com...
Traceback (most recent call last):
  File "/home/labca/acme_tiny.py", line 197, in <module>
    main(sys.argv[1:])
  File "/home/labca/acme_tiny.py", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/home/labca/acme_tiny.py", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for ca.home.domain.com: {u'status': u'invalid', u'challenges': [{u'status': u'invalid', u'validationRecord': [{u'url': u'http://ca.home.comain.com/.well-known/acme-challenge/pgL_bP_1zVbM7ALtCCHPb2kWtE07$
```
I have replaced my real domain with "domain.com".

**Comment by hakwerk** [comment]
Looks like your last line "ValueError: Challenge did not pass for ca.home.domain.com: ...." got truncated, there might be some clue in the 'detail' attribute further on that line.

Also please check your boulder logs (cd /home/labca/boulder; docker-compose logs boulder) when this happens.

**Comment by sakis-tech** [comment]
Thank you for your prompt reply.

Here is the output from `cd /home/labca/boulder; docker-compose logs boulder `

````
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[18967] Failed to execute script docker-compose
```
`

**Comment by hakwerk** [comment]
I'm able to reproduce that last error message when I run that command as the 'labca' user (I usually run it as root ;) ). Please run this command as root:
```
usermod -aG docker labca
```
Now if you change to the 'labca' user again the command should no longer have the permission denied issue.

I'll create a hotfix as the labca user should be in the docker group always.

**Comment by sakis-tech** [comment]
no change even after running `usermod -aG docker labca`

Error persists.

`cd / home / labca / boulder; docker-compose logs boulder`

shows the following

`Error ":" caa :: CAA record for ca.home.domain.com prevents issuance "} `

**Comment by hakwerk** [comment]
Ah that is new, so it is a DNS configuration issue now. Somewhere there is a CAA record set to limit the certificate authorities that may issue certificates for your (main) domain. It checks for CAA records for the FQDN and all parent domains. And ca.home.domain.com is not in that CAA record.

There should also be a log line like "Checked CAA records for ... Response=...". That should give you more info.
Alternatively, if you have dig available ('apt install dnsutils' on debian) then something like this should give the same info:
```
dig ca.home.domain.com -t caa @your.pihole.name.or.ip
dig home.domain.com -t caa @your.pihole.name.or.ip
dig domain.com -t caa @your.pihole.name.or.ip
```

To solve this you either have to change or remove the current CAA record, or set a CAA record on home.domain.com to allow ca.home.domain.com, but pihole DNS does not have this feature.
